# Generated by Django 3.1.7 on 2021-05-06 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('Round trip', 'Round trip'), ('One way', 'One way'), ('Local', 'Local')], default='', max_length=50, null=True)),
                ('pickup_point', models.CharField(max_length=150)),
                ('Pickup_date_time', models.CharField(max_length=70)),
                ('drop_point', models.CharField(max_length=150)),
                ('drop_date', models.CharField(max_length=70)),
                ('selected_car', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=25)),
                ('approx_km_travelling', models.CharField(max_length=50)),
                ('coupon', models.CharField(max_length=150)),
                ('coupon_discount_amount', models.CharField(max_length=50)),
                ('fare', models.CharField(max_length=50)),
                ('advance_payment_medium', models.CharField(max_length=50)),
                ('cash_drop_point', models.CharField(blank=True, max_length=150, null=True)),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('booking_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_Date', models.CharField(max_length=50, unique=True)),
                ('trip_type', models.CharField(choices=[('Round trip', 'Round trip'), ('One way', 'One way'), ('Local', 'Local')], default='', max_length=50, null=True)),
                ('pickup_date_time', models.CharField(max_length=70)),
                ('drop_date', models.CharField(max_length=70)),
                ('km_travelled', models.CharField(max_length=50)),
                ('pickup_point', models.CharField(max_length=150)),
                ('drop_point', models.CharField(max_length=150)),
                ('booked_by_user', models.CharField(max_length=20)),
                ('assigned_driver', models.CharField(max_length=20)),
                ('booked_vehicle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('user_name', models.CharField(max_length=150, null=True)),
                ('mobile_no', models.CharField(max_length=25, null=True)),
                ('wallet_amount', models.CharField(max_length=10, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=60, null=True)),
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
                ('pin_code', models.CharField(max_length=10, null=True)),
                ('mohalla_or_village', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('vehicle_registration_no', models.CharField(max_length=100, null=True)),
                ('vehicle_brand', models.CharField(max_length=100, null=True)),
                ('vehicle_model', models.CharField(max_length=100, null=True)),
                ('insurance_validity', models.CharField(max_length=100, null=True)),
                ('insurance_type', models.CharField(max_length=100, null=True)),
                ('registration_year', models.CharField(max_length=10, null=True)),
                ('km_driven', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('UNDER VARIFICATION', 'UNDER VARIFICATION'), ('ACTIVE', 'ACTIVE'), ('OFFLINE', 'OFFLINE'), ('ON A RIDE', 'ON A RIDE')], default='pending', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('fare_per_km', models.IntegerField()),
                ('air_conditioned', models.BooleanField()),
                ('luggage_capacity', models.IntegerField()),
                ('number_of_seat', models.IntegerField()),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='Vehicles')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='Vehicles')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='Vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
