# Generated by Django 3.2.1 on 2021-05-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
                ('pin_code', models.CharField(max_length=10, null=True)),
                ('mohalla_or_village', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('vehicle_registration_no', models.CharField(max_length=100, null=True)),
                ('vehicle_brand', models.CharField(max_length=100, null=True)),
                ('vehicle_model', models.CharField(max_length=100, null=True)),
                ('insurance_validity', models.CharField(max_length=100, null=True)),
                ('insurance_type', models.CharField(max_length=100, null=True)),
                ('registration_year', models.CharField(max_length=10, null=True)),
                ('km_driven', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('UNDER VARIFICATION', 'UNDER VARIFICATION'), ('ACTIVE', 'ACTIVE'), ('OFFLINE', 'OFFLINE'), ('ON A RIDE', 'ON A RIDE')], default='pending', max_length=50, null=True)),
            ],
        ),
    ]
