# Generated by Django 3.1.7 on 2021-05-13 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
