# Generated by Django 3.1.7 on 2021-05-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='coupon',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
