# Generated by Django 3.2.1 on 2021-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, null=True)),
                ('mobile_no', models.CharField(max_length=25, null=True)),
                ('wallet_amount', models.CharField(max_length=10, null=True)),
                ('email_id', models.EmailField(max_length=60, null=True)),
                ('User_Id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
