# Generated by Django 3.2.1 on 2021-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('fare_per_km', models.IntegerField(max_length=30)),
                ('air_conditioned', models.BooleanField()),
                ('luggage_capacity', models.IntegerField(max_length=50)),
                ('number_of_seat', models.IntegerField(max_length=50)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='images/%y')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='images/%y')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='images/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email_id',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
    ]
