# Generated by Django 3.1.7 on 2021-05-19 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210519_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='refer',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='advance_payment_medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='coupon_discount_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
